CREATE TABLE driver (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    email VARCHAR(255),
    phone VARCHAR(255),
    date_of_birth DATE,
    license_number VARCHAR(255),
    license_state VARCHAR(255),
    license_class VARCHAR(255),
    license_expiry DATE,
    tenant_id VARCHAR(255),
    CONSTRAINT pk_driver PRIMARY KEY (id)
);
